---
version: "2"

services:
  app:
    image: sentry-vue-testing:new-demo-latest
    build: .
    command: "npx serve dist/"
    # volumes:
    #   - ./.git/:/usr/src/app/.git/
    #   - ./public/:/usr/src/app/public/
    #   - ./src/:/usr/src/app/src/
    #   - ./.sentryclirc:/usr/src/app/.sentryclirc
    #   - ./babel.config.js:/usr/src/app/babel.config.js
    #   - ./vue.config.js:/usr/src/app/vue.config.js
    #   - ./yarn.lock:/usr/src/app/yarn.lock
    ports:
      - "5000:5000"
