---
version: "2"

services:
  app:
    image: sentry-vue-testing:latest
    build: .
    command: "npm run deploy"
    volumes:
      - ./.git/:/usr/src/app/.git/
      - ./public/:/usr/src/app/public/
      - ./src/:/usr/src/app/src/
      - ./babel.config.js:/usr/src/app/babel.config.js
      - ./Makefile:/usr/src/app/Makefile
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    env_file: .env
    ports:
      - "9000:9000"
